name: Test variable environment
on:
  push:
    branches:
      - "main"
jobs:
  fetch-env-name:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
    steps:
      - name: Some check on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env_name=prd" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "env_name=dev" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref }}" = "refs/heads/uat" ]; then
            echo "env_name=uat" >> "$GITHUB_OUTPUT"
          else
             echo "Undefined envs"
          fi     
  deploy:
    runs-on: ubuntu-latest
    needs: fetch-env-name
    #environment: ${{ needs.fetch-env-name.outputs.env_name }}

    steps:
      - name:
        run: |
          echo ${{ needs.fetch-env-name.outputs.env_name }}
          echo ${{ vars.MY_NAME }}